version: '2'
services:
    clapforthat-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/ClapForThat/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ClapForThat
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
